<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [6]:
def greeting(name): #function is greeting, accepts a single argument name
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [2]:
greeting("Super Man")

'Hello Super Man!'

In [3]:
greeting(name="Super Man")

'Hello Super Man!'

In [4]:
greeting("Batman")

'Hello Batman! So, nice to meet you!'

In [7]:
greet=greeting(name='Super Man')
print(greet)

Hello Super Man!


In [8]:
print(greeting(name='Super Man'))

Hello Super Man!


In [9]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

In [10]:
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])

### 1.2 Named functions that don’t return

In [12]:
print('hello')

hello


### 1.3 Anonymous/lambda functions

In [15]:
my_short_function = lambda name: f"Hello {name}!"
#lambda returns value of the last statement

In [14]:
my_short_function(name="Super Man")

'Hello Super Man!'

In [16]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [17]:
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [18]:
sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [19]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [20]:
greeting()

'Hello no one!'

In [21]:
?print

In [22]:
print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---') #seperated by --- 
#> I---am---Batman!

I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

### 2.2 A word of caution

## Exercise 1 :  Do you know why?

In [23]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

In [25]:
greeting('Batman')

'Hello Batman! So, nice to meet you!'

In [24]:
greeting('Superman')

'Hello Superman!'

Function requires an output. Using greeting('Batman') gives condition true and returns the next line to give the output 'Hello Batman! So, nice to meet you!'. Using greeting('Superman') gives condition false, next line does not run, return f'Hello {name}!' will run to give an output 'Hello {name}!'.

## Exercise 2 :  Calculator functions

In [56]:
def add(x,y):
    return (x+y) #use return for output for functions,
                 #print does not store values
z=add(1,2)

In [57]:
print(z)

3


In [61]:
def subtract(x,y):
    return (x-y)
z=subtract(2,1)

In [62]:
print(z)

1


In [66]:
def multiply(x,y):
    return (x*y)
z=multiply(2,2)

In [67]:
print(z)

4


In [71]:
def divide(x,y):
    return (x/y)
z=divide(1,3)

In [72]:
print(z)

0.3333333333333333


In [25]:
def divide(x,y):
    if np.any(y==0): #np.any() for at least one true value            #np.all() for all values are true
        print("admonish") #exit kills the kernel
    else:
        return (x/y)
divide(3,0)
divide(3,1)

admonish


3.0

In [20]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

In [74]:
add(x,y)

array([100, 100, 100, 100, 100])

In [75]:
subtract(x,y)

array([-28, -32, -12,  52, -46])

In [76]:
multiply(x,y)

array([2304, 2244, 2464, 1824, 1971])

In [77]:
divide(x,y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

In [28]:
##test
y=np.array([0,0,0])
x=np.array([1,1,1])

In [29]:
divide(x,y)

admonish


In [8]:
(y==0).any

<function ndarray.any>

In [9]:
np.any(y==0)

True

In [10]:
(y!=0).all()

False

In [30]:
np.all(y!=0)

False

In [13]:
y=np.array([1,1,1])

In [14]:
(y==0).any

True

In [17]:
np.any(y==0)

False

In [16]:
(y!=0).all()

True

In [15]:
np.all(y!=0)

True

## Exercise 3 :  max_info() with NumPy

In [17]:
#Answer
def max_info(numbers):
    return np.max(numbers), np.argmax(numbers)

In [18]:
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

In [19]:
max_info(numbers)

(83, 2)

In [ ]:
#Other tries

In [20]:
def max_info(numbers):
    numbers=sorted(numbers)
    return numbers[-1]

In [41]:
max_info(numbers)

83

In [64]:
len(numbers)
index = [i for i in range(0,len(numbers))]

In [55]:
print(index)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [54]:
print(numbers)

[40, 27, 83, 44, 74, 51, 76, 77, 10, 49]


In [57]:
numbers.index(83)

2

In [58]:
zip(index,numbers)

In [66]:
index_number = 0
biggest_number = 0
for i,number in zip(index,numbers):
    print (i,number)
    if biggest_number<number:
        biggest_number=number
        index_number=i

0 40
1 27
2 83
3 44
4 74
5 51
6 76
7 77
8 10
9 49


In [67]:
print(biggest_number)

83


In [70]:
print(index_number)

2


In [2]:
def max_info(numbers):
    return np.max(numbers)
    np.argmax

In [9]:
numbers = [2,4,6,2,6,8]
max_info(numbers)