<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [1]:
import numpy as np

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [4]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  } #Dictionary uses : to separate
#order matters lists --> arrays

### 1.2 Accessing data from a list (or array)

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [9]:
print(py_real_names[2]) #python uses a zero-based index; starts from 0

Stephen Strange


In [10]:
print(np_super_names[1])

Iron Man


In [11]:
print(py_super_names[-1]) #reverse indexing, start from right

Doctor Strange


### 1.3 Accessing data from a dictionary

In [4]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  } #Dictionary uses : to separate keys and values
#order matters lists --> arrays

In [12]:
print(superhero_info["Natasha Romanoff"])

Black Widow


In [13]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [14]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [15]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

In [16]:
print(py_superhero_info[0])

['Natasha Romanoff', 'Black Widow']


## 2 Lists vs. Arrays

### 2.1 Size

In [17]:
#Set up
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [20]:
#2D lists
len(py_list_2d)

10

In [21]:
#2D arrays
len(np_array_2d)

10

In [22]:
np_array_2d.shape #shape is not a function, hence no brackets ()

(10, 2)

### 2.2 Arrays are fussy about type

In [ ]:
#Arrays require a single type of data, whereas lists are more flexible

In [23]:
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [24]:
#Set up
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [25]:
#Lists
py_lists + 10 #will not work

NameError: name 'py_lists' is not defined

In [26]:
#Arrays
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [27]:
#Set up
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [28]:
#Lists
py_list_1 + py_list_2 #separate, 10 values

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [30]:
#Arrays
np_array_1 + np_array_2 #adds values together

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [31]:
#Set up
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [33]:
#Lists
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [34]:
#Arrays
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [35]:
#Set up
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [ ]:
#Lists
py_list**2 # Wil not work!  

In [36]:
#Arrays
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [45]:
#Set up
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [48]:
py_list=[]
if py_list:
    print('A')
else:
    print('B')

B


In [38]:
#Lists
py_list == 3     # Works, but what IS the question?

False

In [43]:
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [40]:
#Arrays
np_array == 3  

array([False, False,  True, False, False])

In [44]:
np_array > 3  

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [49]:
#Setup
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [50]:
#Lists
sum(py_list)     # sum() is a base Python function

15

In [51]:
max(py_list)     # max() is a base Python function

5

In [52]:
min(py_list)     # min() is a base Python function

1

In [53]:
py_list.sum()   # Won't work!

AttributeError: 'list' object has no attribute 'sum'

In [54]:
#Arrays
np_array.sum()

15

In [55]:
np_array.mean()

3.0

In [56]:
np_array.max()

5

In [57]:
np_array.min()

1

## Exercise 1 :  Total recall?

1. Lists and arrays use [] and , between values unlike dictionary which uses {} and :
2. Adding lists together join strings, while adding arrays together adds  element by element. Arrays require single type of data (srting, float, int) while lists are more flexible. For arrays with different types, use np.array(py_list)
3. A dictionary stores data which relates keys to values, uses {} and :

## Exercise 2 :  Index me

In [63]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'

a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [70]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange",
                  }

superhero_info["Natasha Romanoff"] = superhero_info["Natasha Romanoff"].upper()
superhero_info["Tony Stark"] = superhero_info["Tony Stark"].upper()
superhero_info["Stephen Strange"] = superhero_info["Stephen Strange"].upper()
#keys used to access the dictionary, cannot access values directly

print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [76]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61] 
np_numbers=np.array(numbers)

In [82]:
np_numbers_1=np_numbers== 1  
np_numbers_1

array([False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False])

In [84]:
sum(np_numbers_1)

9